# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0b7500f48866f858348c7a4fedb83c7a5437ab8f492938aa7967226ac13db1c58a63a0ab65afb4199d7ca1b5ebbba0f50d7879dc90c1764f44650e4e2c5dfb2

test:
  secret_key_base: 9da815901622f05569a425c28c2f6db1541cb08c985a57a777d175943d9ace381ab12b8d0548bb7270fe8818980c062658f34450698c13b44ffae9e909fb1df8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
